repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
        exclude: \.desktop$
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key

  - repo: local
    hooks:
      - id: create-symlinks
        name: create symlinks
        entry: ./install.sh create_symlinks
        language: system
        stages: [post-commit]
        always_run: true
        pass_filenames: false
