# tmux show-options -g
# sed -r 's/^([^#])/set -g \1/'
# while true; do t=$(stat -c%Y ~/.config/tmux/tmux.conf); [ "$t" == "$ot" ] || { ot=$t; tmux source-file ~/.config/tmux/tmux.conf; }; sleep 2.5; done
# :source-file ~/.config/tmux/tmux.conf

set -g mouse on
set -g base-index 1
set -g set-titles on
set -g set-titles-string '#T (#W)'
set -g clock-mode-colour colour180
set -g clock-mode-style 24
set -g default-terminal "screen-256color"
set -g pane-active-border-style fg=colour220,bg=colour136
set -g pane-border-style fg=colour44,bg=colour19
set -g status-style fg=colour220,bg=colour235
set -g status-interval 30
set -g status-justify left
set -g status-left "#(cat /proc/loadavg)"
set -g status-left-style fg=colour150
set -g status-left-length 15
set -g status-position top
set -g status-right "%Y-%m-%d, %H:%M:%S"
set -g status-right-length 40
set -g status-style fg=colour220,bg=colour235
set-option -g renumber-windows on
set-option -g focus-events on
set-option -g set-clipboard external
set-option -g pane-active-border-style fg=white
set-option -g pane-border-style fg=white
set-window-option -g mode-keys vi
set-window-option -g mode-style "fg=default,bg=default,reverse"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Unbind
unbind Left
unbind Down
unbind Up
unbind Right
unbind C-Left
unbind C-Down
unbind C-Up
unbind C-Right
unbind M-Left
unbind M-Down
unbind M-Up
unbind M-Right
unbind S-Left
unbind S-Down
unbind S-Up
unbind S-Right
unbind -n Up
unbind -n Down
unbind -n Left
unbind -n Right
unbind h
unbind j
unbind k
unbind l
unbind H
unbind J
unbind K
unbind L
unbind q
unbind w
unbind x
unbind n
unbind p
unbind \{
unbind \}
unbind [
unbind ]
unbind u
unbind i
unbind U
unbind I
unbind '"'
unbind %

# Move
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -T copy-mode-vi h send-keys -X cursor-left
bind-key -T copy-mode-vi j send-keys -X cursor-down
bind-key -T copy-mode-vi k send-keys -X cursor-up
bind-key -T copy-mode-vi l send-keys -X cursor-right

# Resize
bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 5
bind-key -r C-k resize-pane -U 5
bind-key -r C-l resize-pane -R 5
bind-key -r M-h resize-pane -L 10
bind-key -r M-j resize-pane -D 10
bind-key -r M-k resize-pane -U 10
bind-key -r M-l resize-pane -R 10

# Split
bind-key H split-window -hb -c "#{pane_current_path}"
bind-key J split-window -v  -c "#{pane_current_path}"
bind-key K split-window -vb -c "#{pane_current_path}"
bind-key L split-window -h  -c "#{pane_current_path}"

# Swap
bind-key u swap-pane -D
bind-key i swap-pane -U
bind-key U swap-window -t :-1
bind-key I swap-window -t :+1

# Window
bind-key , previous-window
bind-key . next-window
bind-key a last-window

# Session
bind-key / choose-tree -Zs -y
bind-key ? choose-tree -Zw -y

# Kill
bind-key q kill-window
bind-key w kill-pane
bind -n q if -F '#{==:#{pane_mode},tree-mode}' 'send x' 'send q'
bind -n w if -F '#{==:#{pane_mode},tree-mode}' 'send x' 'send w'

# Copy/Paste
bind-key v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsel -bi'

# Reload
bind-key r source-file ~/config/tmux/tmux.conf \; display-message "Config reloaded!"
